/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fkino' at '17/01/10 19:08' with Gradle 3.0
 *
 * @author fkino, @date 17/01/10 19:08
 */
public class BowlingScore {
}
