import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'fkino' at '17/01/10 19:08' with Gradle 3.0
 *
 * @author fkino, @date 17/01/10 19:08
 */
public class FrameTest {
	@Test
	public void ストライクでもスペアでもない場合のスコアを求める() {
		int[] fallenPins = {7, 2};
		Frame frame = new Frame(fallenPins);
		assertEquals(9, frame.score());
	}
	
}
