import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'fkino' at '17/01/10 19:08' with Gradle 3.0
 *
 * @author fkino, @date 17/01/10 19:08
 */
public class GameTest {
	@Test
	public void ゲーム全体のスコアを格納する() {
		int[] fallenPins = {5, 4, 0, 0, 10, 0, 9, 1, 6, 3, 7, 0, 6, 2, 10, 0, 10, 0, 1, 9, 5};
		Game game = new Game(fallenPins);
		assertEquals("5, 4, 0, 0, 10, 0, 9, 1, 6, 3, 7, 0, 6, 2, 10, 0, 10, 0, 1, 9, 5", game.toString());
	}

	@Test
	public void ゲーム全体のスコアを計算する() {
		int[] fallenPins = {5, 4, 0, 0, 10, 0, 9, 1, 6, 3, 7, 0, 6, 2, 10, 0, 10, 0, 1, 9, 5};
		Game game = new Game(fallenPins);
		assertArrayEquals(new int[]{9, 9, 29, 45, 54, 61, 69, 90, 110, 125}, game.score());
	}

	@Test
	public void パーフェクトゲームの場合のゲーム全体のスコアを計算する() {
		int[] fallenPins = {10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 10, 10};
		Game game = new Game(fallenPins);
		assertArrayEquals(new int[]{30, 60, 90, 120, 150, 180, 210, 240, 270, 300}, game.score());
	}

	@Test
	public void すべてガターの場合のゲーム全体のスコアを計算する() {
		int[] fallenPins = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
		Game game = new Game(fallenPins);
		assertArrayEquals(new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, game.score());
	}

}
